### ISSUE TITLE
Build error for version 1.7.1

### ISSUE THREAD

**Issue by Gigasnow** [HomeSpan/HomeSpan#519]
**arduinoIDE version**

ArduinoIDE v2.0.3

**espressif/arduino-esp32 version**

2.0.7

**esp32 board**

ESP32C3 DEV Module

**Homespan version**

homespan 1.7.1

**Build Error Message using example code**

/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin 2.cpp:32:1: error: no declaration matches 'LedC::LedC(uint8_t, uint16_t)'
 LedC::LedC(uint8_t pin, uint16_t freq){
 ^~~~
In file included from /Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin 2.cpp:28:
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin.h:53:7: note: candidates are: 'constexpr LedC::LedC(LedC&&)'
 class LedC {
       ^~~~
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin.h:53:7: note:                 'constexpr LedC::LedC(const LedC&)'
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin.h:62:5: note:                 'LedC::LedC(uint8_t, uint16_t, boolean)'
     LedC(uint8_t pin, uint16_t freq, boolean invert=false);
     ^~~~
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin.h:53:7: note: 'class LedC' defined here
 class LedC {
       ^~~~
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin 2.cpp:88:1: error: no declaration matches 'LedPin::LedPin(uint8_t, float, uint16_t)'
 LedPin::LedPin(uint8_t pin, float level, uint16_t freq) : LedC(pin, freq){
 ^~~~~~
In file included from /Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin 2.cpp:28:
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin.h:75:7: note: candidates are: 'constexpr LedPin::LedPin(LedPin&&)'
 class LedPin : public LedC {
       ^~~~~~
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin.h:75:7: note:                 'constexpr LedPin::LedPin(const LedPin&)'
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin.h:78:5: note:                 'LedPin::LedPin(uint8_t, float, uint16_t, boolean)'
     LedPin(uint8_t pin, float level=0, uint16_t freq=DEFAULT_PWM_FREQ, boolean invert=false);   // assigns pin to be output of one of 16 PWM channels initial level and frequency
     ^~~~~~
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/src/extras/PwmPin.h:75:7: note: 'class LedPin' defined here
 class LedPin : public LedC {
       ^~~~~~
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/HomeSpan 2.cpp:2186:1: error: no declaration matches 'SpanPoint::SpanPoint(const char*, int, int, int)'
 SpanPoint::SpanPoint(const char *macAddress, int sendSize, int receiveSize, int queueDepth){
 ^~~~~~~~~
In file included from /Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/HomeSpan 2.cpp:40:
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/HomeSpan.h:863:7: note: candidates are: 'constexpr SpanPoint::SpanPoint(SpanPoint&&)'
 class SpanPoint {
       ^~~~~~~~~
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/HomeSpan.h:863:7: note:                 'constexpr SpanPoint::SpanPoint(const SpanPoint&)'
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/HomeSpan.h:892:3: note:                 'SpanPoint::SpanPoint(const char*, int, int, int, boolean)'
   SpanPoint(const char *macAddress, int sendSize, int receiveSize, int queueDepth=1, boolean useAPaddress=false);
   ^~~~~~~~~
/Users/gigasnow/Documents/Arduino/libraries/HomeSpan/src/HomeSpan.h:863:7: note: 'class SpanPoint' defined here
 class SpanPoint {
       ^~~~~~~~~

exit status 1

Compilation error: exit status 1

**Possible Reason**
I tried to downgrade the homespan version to 1.7.0 and it worked.
I believe that it is because of the new spanupoint feature in version 1.7.1

**Comment by HomeSpan** [comment]
I just tried with Arduino 2.0.3, Arduino-ESP32 2.0.7, and HomeSpan 1.7.1.  No problems compiling for an ESP32-C3.  Can you re-install and try again?

**Comment by HomeKidd** [comment]
I've the same issue when updated to 1.7.1 from 1.7.0, reinstalling HomeSpan library worked for me.  Arduino not always updated the folder structure
