### ISSUE TITLE
Compiler error when building on GitHub

### ISSUE THREAD

**Issue by dkerr64** [HomeSpan/HomeSpan#1115]
I am unable to release a new version of my homekit-ratgdo32 today because of this error when building on [GitHub](https://github.com/ratgdo/homekit-ratgdo32/actions/runs/17895218515)

```
Compiling .pio/build/ratgdo_esp32dev/lib856/HomeSpan/HomeSpan.cpp.o
Compiling .pio/build/ratgdo_esp32dev/lib856/HomeSpan/Network.cpp.o
Compiling .pio/build/ratgdo_esp32dev/lib856/HomeSpan/SRP.cpp.o
In file included from .pio/libdeps/ratgdo_esp32dev/HomeSpan/src/HomeSpan.h:54,
                 from .pio/libdeps/ratgdo_esp32dev/HomeSpan/src/HAP.h:33,
                 from .pio/libdeps/ratgdo_esp32dev/HomeSpan/src/HAP.cpp:35:
.pio/libdeps/ratgdo_esp32dev/HomeSpan/src/Utils.h: In static member function 'static void PushButton::setTouchCycles(uint16_t, uint16_t)':
.pio/libdeps/ratgdo_esp32dev/HomeSpan/src/Utils.h:225:72: error: 'touchSetCycles' was not declared in this scope
  225 |   static void setTouchCycles(uint16_t measureTime, uint16_t sleepTime){touchSetCycles(measureTime,sleepTime);}
      |                                                                        ^~~~~~~~~~~~~~
In file included from .pio/libdeps/ratgdo_esp32dev/HomeSpan/src/HomeSpan.h:54,
                 from .pio/libdeps/ratgdo_esp32dev/HomeSpan/src/HomeSpan.cpp:43:
.pio/libdeps/ratgdo_esp32dev/HomeSpan/src/Utils.h: In static member function 'static void PushButton::setTouchCycles(uint16_t, uint16_t)':
.pio/libdeps/ratgdo_esp32dev/HomeSpan/src/Utils.h:225:72: error: 'touchSetCycles' was not declared in this scope
  225 |   static void setTouchCycles(uint16_t measureTime, uint16_t sleepTime){touchSetCycles(measureTime,sleepTime);}
      |                                                                        ^~~~~~~~~~~~~~
In file included from .pio/libdeps/ratgdo_esp32dev/HomeSpan/src/SRP.h:34,
                 from .pio/libdeps/ratgdo_esp32dev/HomeSpan/src/SRP.cpp:31:
.pio/libdeps/ratgdo_esp32dev/HomeSpan/src/Utils.h: In static member function 'static void PushButton::setTouchCycles(uint16_t, uint16_t)':
.pio/libdeps/ratgdo_esp32dev/HomeSpan/src/Utils.h:225:72: error: 'touchSetCycles' was not declared in this scope
  225 |   static void setTouchCycles(uint16_t measureTime, uint16_t sleepTime){touchSetCycles(measureTime,sleepTime);}
      |                                                                        ^~~~~~~~~~~~~~
*** [.pio/build/ratgdo_esp32dev/lib856/HomeSpan/SRP.cpp.o] Error 1
*** [.pio/build/ratgdo_esp32dev/lib856/HomeSpan/HAP.cpp.o] Error 1
*** [.pio/build/ratgdo_esp32dev/lib856/HomeSpan/HomeSpan.cpp.o] Error 1
In file included from .pio/libdeps/ratgdo_esp32dev/HomeSpan/src/HomeSpan.h:54,
                 from .pio/libdeps/ratgdo_esp32dev/HomeSpan/src/Network.cpp:33:
.pio/libdeps/ratgdo_esp32dev/HomeSpan/src/Utils.h: In static member function 'static void PushButton::setTouchCycles(uint16_t, uint16_t)':
.pio/libdeps/ratgdo_esp32dev/HomeSpan/src/Utils.h:225:72: error: 'touchSetCycles' was not declared in this scope
  225 |   static void setTouchCycles(uint16_t measureTime, uint16_t sleepTime){touchSetCycles(measureTime,sleepTime);}
      |                                                                        ^~~~~~~~~~~~~~
*** [.pio/build/ratgdo_esp32dev/lib856/HomeSpan/Network.cpp.o] Error 1
========================= [FAILED] Took 74.93 seconds =========================

Environment      Status    Duration
---------------  --------  ------------
ratgdo_esp32dev  FAILED    00:01:14.930
==================== 1 failed, 0 succeeded in 00:01:14.930 ====================
Error: Process completed with exit code 1.
```

@mitchjs FYI

**Comment by dkerr64** [comment]
This is with 2.1.4... I see you have just released 2.1.5, I will try with that.

**Comment by dkerr64** [comment]
Still fails with 2.1.5

**Comment by dkerr64** [comment]
It is working with 2.1.5.  Thanks.
