### ISSUE TITLE
'CONFIG_FREERTOS_NUMBER_OF_CORES' was not declared in this scope broken between 2.1.0 and 2.1.1

### ISSUE THREAD

**Issue by mccahan** [HomeSpan/HomeSpan#1045]
Hello! This sketch works fine on 2.1.0, but updating to 2.1.1 and changing nothing else I start getting some compile errors:

```
HomeSpan/src/Utils.cpp: In member function 'void hsWatchdogTimer::enable(uint16_t)':
HomeSpan/src/Utils.cpp:343:17: error: 'CONFIG_FREERTOS_NUMBER_OF_CORES' was not declared in this scope
  343 |   for(int i=0;i<CONFIG_FREERTOS_NUMBER_OF_CORES;i++)
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HomeSpan/src/Utils.cpp:344:63: error: 'xTaskGetIdleTaskHandleForCore' was not declared in this scope; did you mean 'xTaskGetIdleTaskHandleForCPU'?
  344 |     twdtConfig.idle_core_mask |= (ESP_OK==esp_task_wdt_status(xTaskGetIdleTaskHandleForCore(i))) << i;      // replicate existing idle task subscriptions to task watchdog
      |                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                               xTaskGetIdleTaskHandleForCPU
HomeSpan/src/HomeSpan.cpp: In member function 'void Span::begin(Category, const char*, const char*, const char*)':
HomeSpan/src/HomeSpan.cpp:193:17: error: 'CONFIG_FREERTOS_NUMBER_OF_CORES' was not declared in this scope
  193 |   for(int i=0;i<CONFIG_FREERTOS_NUMBER_OF_CORES;i++)
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from HomeSpan/src/HomeSpan.h:53,
                 from HomeSpan/src/HomeSpan.cpp:43:
HomeSpan/src/HomeSpan.cpp:194:67: error: 'xTaskGetIdleTaskHandleForCore' was not declared in this scope; did you mean 'xTaskGetIdleTaskHandleForCPU'?
  194 |     LOG0("\nIDLE-%d Watchdog:  %s",i,(ESP_OK==esp_task_wdt_status(xTaskGetIdleTaskHandleForCore(i)))?"ENABLED":"DISABLED");
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HomeSpan/src/Settings.h:80:109: note: in definition of macro 'LOG0'
   80 | #define LOG0(format,...) do{ if(homeSpan.getLogLevel()>=0)Serial.print ##__VA_OPT__(f)(format __VA_OPT__(,) __VA_ARGS__); }while(0)
      |                                                                                                             ^~~~~~~~~~~
HomeSpan/src/HomeSpan.cpp: In member function 'void Span::pollTask()':
HomeSpan/src/HomeSpan.cpp:245:75: error: 'xTaskGetCoreID' was not declared in this scope; did you mean 'xPortGetCoreID'?
  245 |       LOG0("*** AutoPolling Task started on Core-%d with priority=%d\n\n",xTaskGetCoreID(pollTaskHandle),uxTaskPriorityGet(pollTaskHandle));
      |                                                                           ^~~~~~~~~~~~~~
HomeSpan/src/Settings.h:80:109: note: in definition of macro 'LOG0'
   80 | #define LOG0(format,...) do{ if(homeSpan.getLogLevel()>=0)Serial.print ##__VA_OPT__(f)(format __VA_OPT__(,) __VA_ARGS__); }while(0)
      |                                                                                     
```

# Device
Device is a [Waveshare ESP32-S3 ETH Development Board](https://www.waveshare.com/esp32-s3-eth.htm)

# Library Versions
```
Using board 'esp32s3' from platform in folder: /Users/mccahan/Library/Arduino15/packages/esp32/hardware/esp32/3.0.4
Using core 'esp32' from platform in folder: /Users/mccahan/Library/Arduino15/packages/esp32/hardware/esp32/3.0.4
Using library HomeSpan at version 2.1.1
Using library ArduinoOTA at version 3.0.4
Using library Networking at version 3.0.4
Using library Update at version 3.0.4
Using library Ethernet at version 3.0.4
Using library SPI at version 3.0.4
Using library WiFi at version 3.0.4
Using library ESPmDNS at version 3.0.4
Using library DNSServer at version 3.0.4
Using library ESP32 Async UDP at version 3.0.4
```

Full Sketch
```arduino
#include <HomeSpan.h>
#include "DEV_LED.h"

#if ESP_ARDUINO_VERSION < ESP_ARDUINO_VERSION_VAL(3,0,0)
#include <ETHClass2.h>       //Is to use the modified ETHClass
#define ETH  ETH2
#else
#include <ETH.h>
#endif

#define CONFIG_FREERTOS_NUMBER_OF_CORES 2

#define WAVESHARE_ESP32_S3_ETH
#define ETH_MISO_PIN                    12
#define ETH_MOSI_PIN                    11
#define ETH_SCLK_PIN                    13
#define ETH_CS_PIN                      14
#define ETH_INT_PIN                     10
#define ETH_RST_PIN                     9
#define ETH_ADDR                        1

static bool eth_connected = false;

void onEvent(arduino_event_id_t event) {
  switch (event) {
    case ARDUINO_EVENT_ETH_START:
      Serial.println("ETH Started");
      // The hostname must be set after the interface is started, but needs
      // to be set before DHCP, so set it from the event handler thread.
      ETH.setHostname("esp32-ethernet");
      break;
    case ARDUINO_EVENT_ETH_CONNECTED: Serial.println("ETH Connected"); break;
    case ARDUINO_EVENT_ETH_GOT_IP:
      Serial.println("ETH Got IP");
      Serial.println(ETH);
      eth_connected = true;
      break;
    case ARDUINO_EVENT_ETH_LOST_IP:
      Serial.println("ETH Lost IP");
      eth_connected = false;
      break;
    case ARDUINO_EVENT_ETH_DISCONNECTED:
      Serial.println("ETH Disconnected");
      eth_connected = false;
      break;
    case ARDUINO_EVENT_ETH_STOP:
      Serial.println("ETH Stopped");
      eth_connected = false;
      break;
    default: break;
  }
}

void setup() {
    Serial.begin(115200);
    // homeSpan.useEthernet();
    // homeSpan.enableOTA();
    Network.onEvent(onEvent);

    #ifdef ETH_POWER_PIN
        pinMode(ETH_POWER_PIN, OUTPUT);
        digitalWrite(ETH_POWER_PIN, HIGH);
    #endif

    #if CONFIG_IDF_TARGET_ESP32
        if (!ETH.begin(ETH_TYPE, ETH_ADDR, ETH_MDC_PIN,
                      ETH_MDIO_PIN, ETH_RESET_PIN, ETH_CLK_MODE)) {
            Serial.println("ETH start Failed!");
        }
    #else
        if (!ETH.begin(ETH_PHY_W5500, 1, ETH_CS_PIN, ETH_INT_PIN, ETH_RST_PIN,
                      SPI3_HOST,
                      ETH_SCLK_PIN, ETH_MISO_PIN, ETH_MOSI_PIN)) {
            Serial.println("ETH start Failed!");
        }
    #endif

    homeSpan.begin(Category::Lighting,"device-back-patio-leds");
    new SpanAccessory();
      new Service::AccessoryInformation(); 
        new Characteristic::Identify();
    new DEV_LED(16);
}

void loop() {
    homeSpan.poll();
}

```

**Comment by HomeSpan** [comment]
Are you using PIO?  The error above may be due to the non-standard way PIO determines linkage and compilation order, as well as whether it bothers to link in all files needed.  Others have experience similar issues and the solution seems to set PIO to compile with "deep" linkage.  See https://docs.platformio.org/en/latest/librarymanager/ldf.html for details.

**Comment by HomeSpan** [comment]
Also, curious as to why you implemented a separate ETH class?  The W5500 chip should be supported directly by ETH and hence by HomeSpan.

**Comment by HomeSpan** [comment]
Have you been able to resolve this?

**Comment by HomeSpan** [comment]
Closing.  Please feel free to re-open if needed.
